name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: ' AdoptOpenJDK'
          java-version: '11'

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonarcloud.yml') }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          organization: 'your-sonarcloud-org'  # Reemplaza con tu organización de SonarCloud
          token: ${{ secrets.SONAR_TOKEN }}  # Este token se obtiene de SonarCloud
